# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_regi(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(698, 461)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(60, 80, 571, 351))
        self.background.setStyleSheet("border-image: url(images/register.png)")
        self.background.setText("")
        self.background.setObjectName("background")
        self.username = QtWidgets.QLineEdit(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(270, 200, 251, 51))
        self.username.setStyleSheet("border:none;\n"
"background-color:rgba(0,0,0,0);\n"
"")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(270, 250, 251, 51))
        self.password.setStyleSheet("border:none;\n"
"background-color:rgba(0,0,0,0);\n"
"")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setClearButtonEnabled(False)
        self.password.setObjectName("password")
        self.enter = QtWidgets.QPushButton(self.centralwidget)
        self.enter.setGeometry(QtCore.QRect(280, 320, 241, 61))
        self.enter.setStyleSheet("border:none;\n"
"background-color:rgba(0,0,0,0);")
        self.enter.setText("")
        self.enter.setCheckable(False)
        self.enter.setObjectName("enter")
        self.reset = QtWidgets.QPushButton(self.centralwidget)
        self.reset.setGeometry(QtCore.QRect(130, 320, 121, 61))
        self.reset.setStyleSheet("border:none;\n"
"background-color:rgba(0,0,0,0);")
        self.reset.setText("")
        self.reset.setObjectName("reset")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(570, 120, 41, 51))
        self.exit.setStyleSheet("border:none;\n"
"background-color:rgba(0,0,0,0);")
        self.exit.setText("")
        self.exit.setObjectName("exit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.enter.setShortcut(_translate("MainWindow", "Return"))
